name: AXE

on: [push]
  
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Uses Node.js 16
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm install --location=global wait-on
    - run: npm start &
    # & npx wait-on http://127.0.0.1:8000/
    # - name: Run axe
    - run: |
        npm install --location=global @axe-core/cli
        axe http://127.0.0.1:8000 --exit
