name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get the ENV
      run: echo GITHUB_BASE_REF = ${GITHUB_BASE_REF}

    - name: Code review using JSHint
      uses: moneyforward/jshint-action@v0
